name: beakerx
channels:
  - conda-forge
dependencies:
  - nodejs
  - jupyterlab==0.33.11
  - beakerx
  - ipywidgets
  - traitlets
  - matplotlib
  - pip:
    - jupyterlab_launcher
    - ipywidgets
    - jupyter_contrib_nbextensions
    - jupyterlab_latex
